// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QRBonus.DAL;

#nullable disable

namespace QRBonus.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225124250_added_user_token")]
    partial class added_user_token
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QRBonus.DAL.Models.Banner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Link")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("link");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_banner");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_banner_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_banner_is_deleted");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_banner_region_id");

                    b.ToTable("banner", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.BannerTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BannerId")
                        .HasColumnType("bigint")
                        .HasColumnName("banner_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_banner_translation");

                    b.HasIndex("BannerId")
                        .HasDatabaseName("ix_banner_translation_banner_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_banner_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_banner_translation_is_deleted");

                    b.HasIndex("LanguageId", "BannerId")
                        .IsUnique()
                        .HasDatabaseName("ix_banner_translation_language_id_banner_id");

                    b.ToTable("banner_translation", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Campaign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_campaign");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_campaign_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_campaign_is_deleted");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_campaign_region_id");

                    b.ToTable("campaign", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.CampaignPrize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("PrizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("prize_id");

                    b.HasKey("Id")
                        .HasName("pk_campaign_prize");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_campaign_prize_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_campaign_prize_is_deleted");

                    b.HasIndex("PrizeId")
                        .HasDatabaseName("ix_campaign_prize_prize_id");

                    b.HasIndex("CampaignId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_prize_campaign_id_position");

                    b.ToTable("campaign_prize", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.CampaignTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_campaign_translation");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_translation_campaign_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_campaign_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_campaign_translation_is_deleted");

                    b.HasIndex("LanguageId", "CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_translation_language_id_campaign_id");

                    b.ToTable("campaign_translation", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("device_type");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_number");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verification_code");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_customer_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_customer_is_deleted");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_phone_number");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_customer_region_id");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.CustomerSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expired");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_customer_session");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_customer_session_created_date");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_session_customer_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_customer_session_is_deleted");

                    b.ToTable("customer_session", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Error", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_error");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_error_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_error_is_deleted");

                    b.ToTable("error", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Prize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLeaderboard")
                        .HasColumnType("boolean")
                        .HasColumnName("is_leaderboard");

                    b.Property<string>("Link")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("link");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_prize");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_prize_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_prize_is_deleted");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_prize_region_id");

                    b.ToTable("prize", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.PrizeTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long>("PrizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("prize_id");

                    b.HasKey("Id")
                        .HasName("pk_prize_translation");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_prize_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_prize_translation_is_deleted");

                    b.HasIndex("PrizeId")
                        .HasDatabaseName("ix_prize_translation_prize_id");

                    b.HasIndex("LanguageId", "PrizeId")
                        .IsUnique()
                        .HasDatabaseName("ix_prize_translation_language_id_prize_id");

                    b.ToTable("prize_translation", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Link")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("link");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_product_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_product_is_deleted");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_product_region_id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.ProductCampaign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<long>("Point")
                        .HasColumnType("bigint")
                        .HasColumnName("point");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_campaign");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_product_campaign_campaign_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_product_campaign_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_product_campaign_is_deleted");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_campaign_product_id");

                    b.ToTable("product_campaign", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.ProductTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_translation");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_product_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_product_translation_is_deleted");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_translation_product_id");

                    b.HasIndex("LanguageId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_translation_language_id_product_id");

                    b.ToTable("product_translation", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.QrCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activation_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("HasCustomerConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("has_customer_confirmed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExported")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exported");

                    b.Property<bool>("IsWinReceived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_win_received");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<long?>("NotGivenPrizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("not_given_prize_id");

                    b.Property<DateTime?>("PrizeDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prize_delivery_date");

                    b.Property<long?>("PrizeId")
                        .HasColumnType("bigint")
                        .HasColumnName("prize_id");

                    b.Property<DateTime?>("PrizeReceiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prize_receive_date");

                    b.Property<long>("ProductCampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_campaign_id");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value");

                    b.Property<DateTime?>("WinDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("win_date");

                    b.HasKey("Id")
                        .HasName("pk_qr_code");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_qr_code_created_date");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_qr_code_customer_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_qr_code_is_deleted");

                    b.HasIndex("PrizeId")
                        .HasDatabaseName("ix_qr_code_prize_id");

                    b.HasIndex("ProductCampaignId")
                        .HasDatabaseName("ix_qr_code_product_campaign_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_qr_code_region_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_qr_code_user_id");

                    b.ToTable("qr_code", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("area_code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.HasKey("Id")
                        .HasName("pk_region");

                    b.HasIndex("AreaCode")
                        .IsUnique()
                        .HasDatabaseName("ix_region_area_code");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_region_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_region_is_deleted");

                    b.ToTable("region", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AreaCode = "+995",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("QRBonus.DAL.Models.RegionTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_region_translation");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_region_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_region_translation_is_deleted");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_region_translation_region_id");

                    b.HasIndex("LanguageId", "RegionId")
                        .IsUnique()
                        .HasDatabaseName("ix_region_translation_language_id_region_id");

                    b.ToTable("region_translation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1L,
                            ModifyDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Georgia",
                            RegionId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2L,
                            ModifyDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Georgia",
                            RegionId = 1L
                        });
                });

            modelBuilder.Entity("QRBonus.DAL.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_user_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_user_is_deleted");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_user_name");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            ModifyDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "ANijkOpvmBW5rlnLfPoybM5zNHgrYC8+xVMTEEDQAs/lOdgYkbr2W90wAe73v0kBQg==",
                            Role = 0,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("QRBonus.DAL.Models.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expired");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_session");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_user_session_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_user_session_is_deleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_session_user_id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Banner", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_banner_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.BannerTranslation", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Banner", "Banner")
                        .WithMany("Translations")
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_banner_translation_banner_banner_id");

                    b.Navigation("Banner");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Campaign", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.CampaignPrize", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_prize_campaign_campaign_id");

                    b.HasOne("QRBonus.DAL.Models.Prize", "Prize")
                        .WithMany()
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_prize_prizes_prize_id");

                    b.Navigation("Campaign");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.CampaignTranslation", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Campaign", "Campaign")
                        .WithMany("Translations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_translation_campaign_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Customer", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.CustomerSession", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_session_customer_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Prize", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prize_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.PrizeTranslation", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Prize", "Prize")
                        .WithMany("Translations")
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prize_translation_prize_prize_id");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Product", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.ProductCampaign", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Campaign", "Campaign")
                        .WithMany("ProductCampaigns")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_campaign_campaign_campaign_id");

                    b.HasOne("QRBonus.DAL.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_campaign_products_product_id");

                    b.Navigation("Campaign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.ProductTranslation", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Product", "Product")
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_translation_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.QrCode", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_qr_code_customer_customer_id");

                    b.HasOne("QRBonus.DAL.Models.Prize", "Prize")
                        .WithMany()
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_qr_code_prize_prize_id");

                    b.HasOne("QRBonus.DAL.Models.ProductCampaign", "ProductCampaign")
                        .WithMany()
                        .HasForeignKey("ProductCampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_qr_code_product_campaign_product_campaign_id");

                    b.HasOne("QRBonus.DAL.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_qr_code_regions_region_id");

                    b.HasOne("QRBonus.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_qr_code_users_user_id");

                    b.Navigation("Customer");

                    b.Navigation("Prize");

                    b.Navigation("ProductCampaign");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.RegionTranslation", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.Region", "Region")
                        .WithMany("Translations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_region_translation_region_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.UserSession", b =>
                {
                    b.HasOne("QRBonus.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_session_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Banner", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Campaign", b =>
                {
                    b.Navigation("ProductCampaigns");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Prize", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Product", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("QRBonus.DAL.Models.Region", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
